/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'no' at '16. 9. 23 오전 10:43' with Gradle 2.14.1
 *
 * @author no, @date 16. 9. 23 오전 10:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
